### ISSUE TITLE
Enable Clustering of Map Markers in the Tree Profile Widget

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-widgets#18]
- [x] Implement Clustering of Contributions
- [x] Sum total trees to form a cluster

**Comment by norbertschuler** [comment]
Mapbox supports clusters, but that would require some changes in our widget logic (1) transforming the contributions to a GeoJSON data source which then can be added with `map.addSource`  and (2) doing the custom marker styling by adding a layer with `map.addLayer` as documented in this example: https://docs.mapbox.com/mapbox-gl-js/example/cluster/
