### ISSUE TITLE
Dark theme of tree-map can not properly display text links

### ISSUE THREAD

**Issue by norbertschuler** [Plant-for-the-Planet-org/planet-widgets#19]
**Describe the bug**
The links for the profile and the planet website are written with white color which is not readable on white parts of the map.

**Is it on a Production or Development Build?**
production

**Screenshots**
<img width="760" alt="Bildschirmfoto 2021-01-31 um 13 42 43" src="https://user-images.githubusercontent.com/1532418/106384271-38a7d980-63ca-11eb-93ea-7be7353b3ac6.png">

**Comment by sagararyal** [comment]
Todo:

- [ ] Create a dark theme version of vector map in arcgis
