### ISSUE TITLE
Auto refresh all widgets every 10 seconds.

### ISSUE THREAD

**Issue by sagararyal** [Plant-for-the-Planet-org/planet-widgets#26]
By default refresh widgets every 10 seconds.

Add a prop

refresh: slow  = 10 seconds
refresh: fast  = 5 seconds
refresh: none = off

Default behavior is slow.

Important: While refreshing; do not refetch the contribution endpoint.  re drawing on Mapbox can cause CPU to cry.

Only leaderboard and profile endpoint should be enough to be refreshed automatically.

**Comment by norbertschuler** [comment]
Hopefully this won't result into to much load on the backend by API calls.

**Comment by sagararyal** [comment]
@norbertschuler if this does take a hit, we can update the widget to change its behavior. But I hope it won't be an issue.
