### ISSUE TITLE
Clustering Bug when Zooming in as close as possible

### ISSUE THREAD

**Issue by delightedMatt** [Plant-for-the-Planet-org/planet-widgets#34]
If you continue zooming in on a tree cluster, it will at some point just show one of the tree-contributions, even if all the tree-contributions have the same location.

E.g.:
Sagar's Yucatán Trees
https://user-images.githubusercontent.com/18365824/107541283-411cc300-6bc7-11eb-9e33-f67ee5f2a483.mp4

E.g.:
Matthias's I don't know where Trees
https://user-images.githubusercontent.com/18365824/107541299-4712a400-6bc7-11eb-92bc-ee7399cefe1f.mp4

**Comment by sagararyal** [comment]
This will happen often if many trees are planted on same project, I suggest continuing with clustering in higher zoom levels.
@sarveshpro do you want to give a try?

**Comment by sarveshpro** [comment]
`clusterMaxZoom` is by default one less than `maxZoom` of the map. I have set the `maxZoom` to 16 and `clusterMaxZoom` to 24, this combination seems to work. Pl check #35
