### ISSUE TITLE
Background circle of logo is missing 

### ISSUE THREAD

**Issue by harshvitra** [Plant-for-the-Planet-org/planet-widgets#50]
<img width="228" alt="Screenshot 2021-03-18 at 5 18 52 PM" src="https://user-images.githubusercontent.com/25605193/111621531-1b11c080-880e-11eb-8337-3e2e7378b0af.png">

**Comment by norbertschuler** [comment]
@harshvitra I am sorry, I cannot reproduce this. Can you please tell us which browse, operating system and deployment you have experienced this with? Otherwise please close if fixed.
